config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  root 'application#home'
  resources :games do
    resources :rounds
    match '/delete/rounds', to: 'rounds#destroy', via: [:get, :post]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :game
  belongs_to :user
  belongs_to :question

    def self.category_id(id)
    Game.find_by(id: id).category_id
  end
  
  def correct?(answer)
      @user = User.find_by(id: self.user_id)
    @q = Question.find_by(id: self.question_id)
    if @q.correct_answer == self.user_answer
      @user.points = @user.points + @q.points
      @user.save
    "Yes that is correct, you earned #{@q.points}"
    else
      @user.points = @user.points - @q.points
      @user.save
   "Sorry, that was wrong, the correct answer is #{@q.correct_answer}, your answer was #{self.user_answer}"
  end
end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :current_game
  def new
    @game = current_game
    @q = Question.randon_from_category(@game.category_id, @game.difficulty)
    @round = Round.new
  end

  def create
    @round = Round.create(round_params)
    @round.save
    redirect_to edit_game_round_path(@game.id, @round.id)
  end

  def show
  end

  def edit
    @game = current_game
    @round = Round.find_by(id: params[:id])
    @q = Question.find_by(id: @round.question_id)
  end

  def update
    @rounds = Round.all
    @round = Round.find_by(id: params[:id])
    @round.update(round_params)
    flash[:msg] = @round.correct?(params[:user_answer])
    render :show
  end

  def destroy
    current_user.questions.delete_all
    @rounds = Round.all
    @rounds.delete_all
    redirect_to root_path
  end

  private

  def round_params
    params.require(:round).permit(:game_id, :user_id, :question_id, :user_answer)
  end
end

app/views/rounds/_begin.html.erb
<h1>Before we begin</h1>
<p>To whom have yet to play this game,</p>
<p>Each round has one question and, each question is worth 20 points, if you get the question correct you'll be given 20 points</p>
<p>However, in the event that you do not get the answer correct 20 points will be taken from you whether or not you have more than zero and, yes you can have negitive points <strong>Good Luck!!</strong></p>
<%= form_for [@game, @round]  do |f|%>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.hidden_field :game_id, value: current_game.id %> 
<%= f.hidden_field :question_id, value: @q.id %> 

<%= f.submit "Start Round" %>
<% end %>

app/views/rounds/_next.html.erb
<h1>Lets Continue, Shall We</h1>
<%= form_for [@game, @round]  do |f|%>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.hidden_field :game_id, value: current_game.id %> 
<%= f.hidden_field :question_id, value: @q.id %> 


<%= f.submit "Next Round"%>
<% end %>

app/views/rounds/edit.html.erb
<h2><%= @q.to_quot %></h2>
<%= form_for [@game, @round] do |f| %>
<h3>Is it</h3>
<%= f.hidden_field :user_id, value: current_user.id %>
<%= f.hidden_field :game_id, value: current_game.id %>
<%= f.hidden_field :question_id, value: @q.id %>
  <ul>
<%= f.collection_radio_buttons :user_answer, @q.parse_data, :to_s, :to_s, include_blank: false  do |b|%>
 <li><%= b.radio_button + b.label(:class => "collection_radio_buttons icon-star") %></li> <br>
<% end %>
</ul>
 <br>

<br>
    <%= f.submit "submit question"%>
<% end %>

app/views/rounds/new.html.erb
<% if current_game.rounds.count < 1 %>
  <%= render "begin" %>
<% else %>
  <%= render "next" %>
<% end %>

app/views/rounds/show.html.erb
 <% flash.each do |type, msg| %>
  <div>
    <h1><%= msg %></h1>
    <h2><%= current_user.points %></h2>
  </div>
<% end %>
 <% if current_user.questions.count < current_game.num_of_rounds %>
<%= link_to "only one more click from next question", new_game_round_path(@game)%>
<% else %>
<%= link_to 'End Game', game_delete_rounds_path %>
<% end %>